# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-hostmanager")
	system("vagrant plugin install vagrant-hostmanager")
	raise("Plugin installed. Run command again.");
end

Vagrant.configure("2") do |config|
  config.vm.box = "blinkreaction/boot2docker"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.define 'docker-ci-demo' do |node|
    node.vm.hostname = 'docker-ci-demo'
    node.vm.network :private_network, ip: "192.168.50.42"
#    node.vm.network :private_network, type: "dhcp"
#    node.hostmanager.aliases = %w(e6520)
  end
end
