# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "blinkreaction/boot2docker"
  config.vm.hostname = 'docker-ci-demo'
  config.vm.network :private_network, ip: "192.168.50.42"
end
